# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12image_stream.proto\"\xae\x01\n\nImageFrame\x12\x13\n\x0b\x63olour_data\x18\x01 \x01(\x0c\x12\x12\n\ndepth_data\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\x12\n\n\x02\x66x\x18\x06 \x01(\x02\x12\n\n\x02\x66y\x18\x07 \x01(\x02\x12\x0b\n\x03ppx\x18\x08 \x01(\x02\x12\x0b\n\x03ppy\x18\t \x01(\x02\x12\x13\n\x0b\x64\x65pth_scale\x18\n \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_stream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEFRAME._serialized_start=23
  _IMAGEFRAME._serialized_end=197
# @@protoc_insertion_point(module_scope)
