import sys
import os
import cv2
import numpy as np

# --- 1. SETUP REALSENSE PATHS (For Pi 5) ---
# This ensures Python finds the library you built from source
realsense_dir = "/home/pi5/librealsense/build/Release"
if realsense_dir not in sys.path:
    sys.path.append(realsense_dir)

try:
    import pyrealsense2 as rs
except ImportError:
    print(f"❌ Error: Could not find pyrealsense2 in {realsense_dir}")
    sys.exit(1)

from ultralytics import YOLO

# --- 2. CONFIGURATION ---
# Point this to the folder generated by the export command above
MODEL_PATH = "./models/segmentation_nano_openvino_model"

if not os.path.exists(MODEL_PATH):
    print(f"❌ CRITICAL: Model folder not found at: {MODEL_PATH}")
    print("   Did you run: 'yolo export model=... format=openvino'?")
    sys.exit(1)

# Load model with task='segment' to prevent the "KeyError: 26" crash
print("Loading OpenVINO model...")
model = YOLO(MODEL_PATH, task="segment")

# --- 3. REALSENSE PIPELINE SETUP ---
pipeline = rs.pipeline()
config = rs.config()
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)

print("Starting RealSense stream... (Wait for auto-exposure)")
pipeline.start(config)

try:
    while True:
        # Get frames from RealSense instead of cap.read()
        frames = pipeline.wait_for_frames()
        color_frame = frames.get_color_frame()
        if not color_frame:
            continue

        # Convert to numpy array
        frame = np.asanyarray(color_frame.get_data())
        H, W = frame.shape[:2]

        # Run YOLO inference (OpenVINO engine used automatically)
        results = model.predict(frame, imgsz=640, conf=0.75, verbose=False)
        r = results[0]

        # Safe plotting (catches the "ghost class" crash if it happens)
        try:
            annotated_frame = r.plot()
        except KeyError:
            annotated_frame = frame.copy()

        # ----------------------------------------------------------------------
        # ⭐ MANUAL UPSAMPLING OF MASKS TO FULL RES
        # ----------------------------------------------------------------------
        if r.masks is not None:
            # .cpu() is safe here because OpenVINO is already on CPU
            lowres_masks = r.masks.data.cpu().numpy()
            full_masks = []

            for m in lowres_masks:
                up = cv2.resize(m, (W, H), interpolation=cv2.INTER_NEAREST)
                full_masks.append(up)

            full_masks = np.array(full_masks)

            # ------------------------------------------------------------------
            # Fit ellipses
            # ------------------------------------------------------------------
            for mask in full_masks:
                mask_uint8 = (mask * 255).astype(np.uint8)
                _, binary = cv2.threshold(mask_uint8, 128, 255, cv2.THRESH_BINARY)

                contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                if len(contours) == 0:
                    continue

                c = max(contours, key=cv2.contourArea)
                # Filter small noise
                if len(c) < 5:
                    continue

                ellipse = cv2.fitEllipse(c)
                (cx, cy), (MA, ma), angle = ellipse

                # Draw ellipse
                cv2.ellipse(annotated_frame, ellipse, (255, 0, 0), 2)

                # -----------------------------
                # Draw major & minor axis lines
                # -----------------------------
                theta = np.deg2rad(angle)

                # Major axis (red)
                dx_major = (MA / 2) * np.cos(theta)
                dy_major = (MA / 2) * np.sin(theta)
                p1_major = (int(cx - dx_major), int(cy - dy_major))
                p2_major = (int(cx + dx_major), int(cy + dy_major))
                cv2.line(annotated_frame, p1_major, p2_major, (0, 0, 255), 2)

                # Minor axis (green)
                dx_minor = (ma / 2) * np.sin(theta)
                dy_minor = (ma / 2) * np.cos(theta)
                p1_minor = (int(cx - dx_minor), int(cy + dy_minor))
                p2_minor = (int(cx + dx_minor), int(cy - dy_minor))
                cv2.line(annotated_frame, p1_minor, p2_minor, (0, 255, 0), 2)

                # -----------------------------
                # Angle (major axis orientation)
                # -----------------------------
                angle_major = angle
                if MA < ma:
                    angle_major += 90

                angle_major = abs((angle_major + 90) % 180 - 90)

                # -----------------------------
                # Display text (lengths + angle)
                # -----------------------------
                text_y = int(cy)

                cv2.putText(annotated_frame, f"Angle: {angle_major:.1f} deg",
                            (int(cx), text_y), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

                cv2.putText(annotated_frame, f"Major: {MA:.1f}px",
                            (int(cx), text_y + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

                cv2.putText(annotated_frame, f"Minor: {ma:.1f}px",
                            (int(cx), text_y + 40), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

        cv2.imshow("Pi 5: YOLOv8 + RealSense + OpenVINO", annotated_frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

finally:
    pipeline.stop()
    cv2.destroyAllWindows()